### ISSUE TITLE
Current module view fails bc of "Identifier 'gql' has already been declared" syntax error

### ISSUE THREAD

**Issue by eunicode** [downshift-js/downshift-examples#40]
When I open a file in the examples directory, such as `hooks > useCombobox > basic-usage.js` (https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useCombobox/basic-usage.js)
and go to "Current Module View", I get this error: 
```
SyntaxError: /src/shared.js: Identifier 'gql' has already been declared (5:8)

  3 | import {gql} from '@apollo/client'
  4 | import styled from 'react-emotion'
> 5 | import {gql} from '@apollo/client'
```

**Comment by silviuaavram** [comment]
Oups, sorry about that!
