### ISSUE TITLE
The final example isn't loading for me

### ISSUE THREAD

**Issue by dwertheimer** [downshift-js/downshift-examples#46]
The Multi-Create example seems to have a bug on CodeSandbox

https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/ordered-examples/02-complete-autocomplete.js&moduleview=1&file=/src/downshift/ordered-examples/05-multi-create.js

I could be doing something wrong but the other examples worked fine.

<img width="1079" alt="Screen Cap 2023-02-01 at 21 19 03@2x" src="https://user-images.githubusercontent.com/8949588/216238287-28888de6-0dee-4543-b073-d895e0260684.png">

**Comment by silviuaavram** [comment]
Should be fixed now. Thanks for reporting!
